### ISSUE TITLE
Resize Image only if it exceeds a size limit

### ISSUE THREAD

**Issue by Vaibhav2002** [onseok/peekaboo#50]
Is it possible to have a feature like
Image will only get resized if it exceeds the 1MB limit or any limit we specify?

**Comment by onseok** [comment]
Hi @Vaibhav2002, it's possible to add a feature where images are resized only if they exceed a specified size limit, like 1MB. Great suggestion! I'll work on adding this to the next release.

**Comment by LaatonWalaBhoot** [comment]
@onseok Is it possible to always resize below a certain limit?
The problem that I am facing is that on iOS clicked images are sometimes 30mbs in size
Is it possible to always resize down below 1 MB?
