### ISSUE TITLE
Whenever i run the ImagePicker after selecting the desired image i get this error

### ISSUE THREAD

**Issue by kwesiamartey** [onseok/peekaboo#57]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = uiComponent.UploadCompanyDocument)

**Comment by kwesiamartey** [comment]
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = uiComponent.UploadCompanyDocument)

**Comment by onseok** [comment]
Hi @kwesiamartey, could you provide a smaller reproducer?

**Comment by kwesiamartey** [comment]
val multipleImagePicker =
            rememberImagePickerLauncher(
                selectionMode = SelectionMode.Multiple(maxSelection = 2),
                scope = scope,
                // Resize options are customizable. Default is set to 800 x 800 pixels.
                resizeOptions = ResizeOptions(width = 400, height = 400),
                onResult = { byteArrays ->
                    try {
                        images = byteArrays.map { byteArray ->
                            byteArray.toImageBitmap()
                        }
                        byteArrays.onEach {

                        }

                        companyFile.add(
                            CompanyFile(
                                fileData = byteArrays[0],
                                fileExt = "jpg",
                                fileName = "ID Document"
                            )
                        )

                    } catch (e: Exception) {
                        // Log or print the exception information
                        e.printStackTrace()
                    }
                },
            )

**Comment by onseok** [comment]
Hi @kwesiamartey, it looks like the issue you're facing with the `Parcelable encountered IOException` error isn't related to the image picker library. Instead, the problem seems to stem from how the `CompanyFile` object is being serialized. 
I'd recommend double-checking that `CompanyFile` and all its member variables are properly implementing Serializable interface.

**Comment by kwesiamartey** [comment]
this is a reproducer of CompanyFile   

@Serializable
data class CompanyFile(
    @SerialName("file_data")
    var fileData: ByteArray?=null,
    @SerialName("file_ext")
    var fileExt: String? = null,
    @SerialName("file_name")
    var fileName: String? = null
)
