### ISSUE TITLE
can't install 0.4.3

### ISSUE THREAD

**Issue by masterofdaemon** [onseok/peekaboo#68]
I have the same issue with shrink image width like issue : #44  with 0.4.2

I should update , but I've got  error : Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.github.team-preat:peekaboo-ui:0.4.3.
Required by:
    project :composeApp
Cause 2: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.github.team-preat:peekaboo-image-picker:0.4.3.
Required by:
    project :composeApp

**Comment by onseok** [comment]
Hi @masterofdaemon, you might have used `io.github.team-preat` as the group id, but now you need to update your Gradle dependencies to use the new group id, which is `io.github.onseok`.
