### ISSUE TITLE
Capture and convert camera buttons are in a wrong position

### ISSUE THREAD

**Issue by shtolik** [onseok/peekaboo#71]
In 0.5.0 version i think something got broken with showing overlay button "the previous way" via PeekabooCamera fun to which you pass captureIcon and convertIcon composables. They are shown in TopStart for me instead of the alignment I pass in the modifier (bottomCenter and bottomEnd). 

I feel that it's because of of this function: 

```
@Composable
private fun CompatOverlay(
    state: PeekabooCameraState,
    captureIcon: @Composable (onClick: () -> Unit) -> Unit,
    convertIcon: @Composable (onClick: () -> Unit) -> Unit,
    progressIndicator: @Composable () -> Unit,
) {
    Box {
        captureIcon(state::capture)
        convertIcon(state::toggleCamera)
        if (state.isCapturing) {
            progressIndicator()
        }
    }
}
```

Which has a default Box containing them. So it seems like it's not filling maximum size of parent so the modifier of captureIcon and convertIcons are not having effect on alignment. 

<img width="385" alt="Screenshot 2024-03-12 at 9 30 17" src="https://github.com/onseok/peekaboo/assets/6986441/5fdb2f15-cae6-4f15-a18c-eb2684e1b274">

**Comment by shtolik** [comment]
Adding fillMaxSize seems to fix it. And that's what's done for the overlay in a "new" PeekabooCameraView with state: 

```
@Composable
internal fun PeekabooCameraView(
    modifier: Modifier = Modifier,
    onCapture: (ByteArray?) -> Unit,
    onBack: () -> Unit,
) {
    val state = rememberPeekabooCameraState(onCapture = onCapture)
    Box(modifier = modifier) {
        PeekabooCamera(
            state = state,
            modifier = Modifier.fillMaxSize(),
            permissionDeniedContent = {
                PermissionDenied(
                    modifier = Modifier.fillMaxSize(),
                )
            },
        )
        CameraOverlay(
            isCapturing = state.isCapturing,
            onBack = onBack,
            onCapture = { state.capture() },
            onConvert = { state.toggleCamera() },
            modifier = Modifier.fillMaxSize(),
        )
    }
}
```

**Comment by vshkl** [comment]
@onseok, hello. I made a small [PR](https://github.com/onseok/peekaboo/pull/90) that fixes up the iOS side of this issue. I would appreciate it if someone have a look and merge it if it's OK. Thanks.
