### ISSUE TITLE
Exif info about image rotation/flipping is not respected when selecting from gallery

### ISSUE THREAD

**Issue by shtolik** [onseok/peekaboo#73]
Doesn't work also in the sample app when selecting single or multiple images 
[ from this repo](https://github.com/ianare/exif-samples/tree/master/jpg/orientation). 

For example this one: 
https://github.com/ianare/exif-samples/blob/master/jpg/orientation/landscape_5.jpg
![landscape_5](https://github.com/onseok/peekaboo/assets/6986441/735d3f9f-5708-4377-b06c-963caf2731f9)

Show after import like this in preview: 

<img width="376" alt="Screenshot 2024-03-12 at 10 27 21" src="https://github.com/onseok/peekaboo/assets/6986441/474e6d01-ec75-48ef-8bda-d275852b3608">

**Comment by onseok** [comment]
Hi @shtolik, this issue will be fixed in the upcoming release.
Thank you for reporting 👍
